
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=marker'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '62396:5432'  #  to host port 62396, Map container port 5432
    volumes:
      - './pgvector-data:/var/lib/postgresql/data'  # Persist data to host directory


