
 zimsec-history-2019-ms Marking Scheme


 Question 1
 What caused the death of King Kharma?
 Expected Answer : King kharma's cause of death is still unknown in the history books but its suspected to be cancer.

 Question 2
 Name any one entity included in African seven colors meal?
 Expected Answer : African seven colors meal include rice, beef, green salad, potatoes,carrots, beetroot and a soda.

 Question 3
 When was Walker available in the office?
 Expected Answer : Walker was available only on Saturday or Sunday.


